### PR TITLE
Cf feature/web platform

### PR DESCRIPTION
**Pull request by chrisfenos**
- Web Platform 
- New project structure and layout 
- Network stats displayed via iFrame
- blockscouts explorer not currently embedded due to 'X-Frame-Options'
- Bridge ui instructions added for users when interacting with the bridge ui
- Sample blog section for content
- Sample Goerli about information displayed in about section 
- Goerli UI roadmap added 

** things needed to be done - Faucet & Embedded explorer

### CODE REVIEW

**Comment by ChainSafeSystems** [comment]
`Unhandled Rejection (TypeError): Cannot read property 'getTransactionCount' of null`
I am having issues with the bridge using Brave with "shield" down. Waiting on someone else to duplicate this issue as it is not an issue on @CFDevelopment's machine. 

Chris deduced that the Bridge is down. We are working on a solution for this.

**Comment by chrisfenos** [comment]
@ChainSafe It would have appeared to be an issue with the node. The node has been changed and the issue seems to be resolved. Could you verify?

**Comment by GregTheGreek** [comment]
It appears on compile we have a bit of a bug @CFDevelopment I haven't gone through the code yet, but I'm doing that as we speak.
Code output:
```
Failed to compile.

./node_modules/web3-providers-ws/src/index.js
Module not found: Can't resolve 'websocket' in '/Users/gregmarkou/Jobs/Jobs/ChainSafe/goerli/GoethBridgeUI/node_modules/web3-providers-ws/src'
```

**Comment by GregTheGreek** [comment]
Problem solved using node v10

**Review by GregTheGreek — APPROVED** [review]
Looks good to me

**Pull request merged**
